main : com.clashwars.cwbounty.CWBounty
name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
depend: [CWCore]
commands:
  bounty:
    description: Main bounty command
    usage: /<command>
    aliases: [bounties]